name: Enterprise AI Agent CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  # TUGAS 1: Mengetes Otot Gateway (Golang)
  build-golang:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: '1.21' 

    - name: Build Golang API
      # Beritahu robot untuk masuk ke kamar Golang dulu
      working-directory: ./golang-api
      run: go build -v ./...

  # TUGAS 2: Mengetes Otak AI (Python)
  build-python:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Check Python Syntax
      # Beritahu robot untuk masuk ke kamar Python dulu
      working-directory: ./python-agent
      run: python -m py_compile main.py